-- MySQL Script generated by MySQL Workbench
-- Mon May  6 18:31:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_agents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_agents` (
  `idTBL_AGENTS` INT NOT NULL AUTO_INCREMENT,
  `AGENT` VARCHAR(45) NOT NULL,
  `PICK_RATE` VARCHAR(45) NOT NULL,
  `ACS` DOUBLE NOT NULL,
  `K/D` DOUBLE NOT NULL,
  PRIMARY KEY (`idTBL_AGENTS`),
  UNIQUE INDEX `idTBL_AGENTS_UNIQUE` (`idTBL_AGENTS` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_maps` (
  `idTBL_MAPS` INT NOT NULL AUTO_INCREMENT,
  `MAP` VARCHAR(45) NOT NULL,
  `PLAYED` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_MAPS`),
  UNIQUE INDEX `MAP_UNIQUE` (`MAP` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_agents_has_tbl_maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_agents_has_tbl_maps` (
  `TBL_AGENTS_idTBL_AGENTS` INT NOT NULL AUTO_INCREMENT,
  `TBL_MAPS_idTBL_MAPS` INT NOT NULL,
  PRIMARY KEY (`TBL_AGENTS_idTBL_AGENTS`, `TBL_MAPS_idTBL_MAPS`),
  INDEX `fk_TBL_AGENTS_has_TBL_MAPS_TBL_MAPS1_idx` (`TBL_MAPS_idTBL_MAPS` ASC) VISIBLE,
  INDEX `fk_TBL_AGENTS_has_TBL_MAPS_TBL_AGENTS1_idx` (`TBL_AGENTS_idTBL_AGENTS` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_AGENTS_has_TBL_MAPS_TBL_AGENTS1`
    FOREIGN KEY (`TBL_AGENTS_idTBL_AGENTS`)
    REFERENCES `mydb`.`tbl_agents` (`idTBL_AGENTS`),
  CONSTRAINT `fk_TBL_AGENTS_has_TBL_MAPS_TBL_MAPS1`
    FOREIGN KEY (`TBL_MAPS_idTBL_MAPS`)
    REFERENCES `mydb`.`tbl_maps` (`idTBL_MAPS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_players` (
  `idTBL_PLAYERS` INT NOT NULL AUTO_INCREMENT,
  `PLAYER` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `TEAM` VARCHAR(45) NOT NULL,
  `ACS` DOUBLE NOT NULL,
  `K/D` DOUBLE NOT NULL,
  PRIMARY KEY (`idTBL_PLAYERS`),
  UNIQUE INDEX `PLAYER_UNIQUE` (`PLAYER` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_players_has_tbl_maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_players_has_tbl_maps` (
  `TBL_PLAYERS_idTBL_PLAYERS` INT NOT NULL,
  `TBL_MAPS_idTBL_MAPS` INT NOT NULL,
  PRIMARY KEY (`TBL_PLAYERS_idTBL_PLAYERS`, `TBL_MAPS_idTBL_MAPS`),
  INDEX `fk_TBL_PLAYERS_has_TBL_MAPS_TBL_MAPS1_idx` (`TBL_MAPS_idTBL_MAPS` ASC) VISIBLE,
  INDEX `fk_TBL_PLAYERS_has_TBL_MAPS_TBL_PLAYERS1_idx` (`TBL_PLAYERS_idTBL_PLAYERS` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_PLAYERS_has_TBL_MAPS_TBL_MAPS1`
    FOREIGN KEY (`TBL_MAPS_idTBL_MAPS`)
    REFERENCES `mydb`.`tbl_maps` (`idTBL_MAPS`),
  CONSTRAINT `fk_TBL_PLAYERS_has_TBL_MAPS_TBL_PLAYERS1`
    FOREIGN KEY (`TBL_PLAYERS_idTBL_PLAYERS`)
    REFERENCES `mydb`.`tbl_players` (`idTBL_PLAYERS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_teams` (
  `idTBL_TEAMS` INT NOT NULL AUTO_INCREMENT,
  `TEAM` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTBL_TEAMS`),
  UNIQUE INDEX `TEAM_UNIQUE` (`TEAM` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_players_has_tbl_agents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_players_has_tbl_agents` (
  `ID_tbl_players_has_tbl_agentscol` INT NOT NULL AUTO_INCREMENT,
  `tbl_players_idTBL_PLAYERS` INT NOT NULL,
  `tbl_agents_idTBL_AGENTS` INT NOT NULL,
  PRIMARY KEY (`ID_tbl_players_has_tbl_agentscol`, `tbl_players_idTBL_PLAYERS`, `tbl_agents_idTBL_AGENTS`),
  INDEX `fk_tbl_players_has_tbl_agents_tbl_agents1_idx` (`tbl_agents_idTBL_AGENTS` ASC) VISIBLE,
  INDEX `fk_tbl_players_has_tbl_agents_tbl_players1_idx` (`tbl_players_idTBL_PLAYERS` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_players_has_tbl_agents_tbl_players1`
    FOREIGN KEY (`tbl_players_idTBL_PLAYERS`)
    REFERENCES `mydb`.`tbl_players` (`idTBL_PLAYERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_players_has_tbl_agents_tbl_agents1`
    FOREIGN KEY (`tbl_agents_idTBL_AGENTS`)
    REFERENCES `mydb`.`tbl_agents` (`idTBL_AGENTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_teams_has_tbl_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_teams_has_tbl_players` (
  `ID_tbl_teams_has_tbl_playerscol` INT NOT NULL AUTO_INCREMENT,
  `tbl_teams_idTBL_TEAMS` INT NOT NULL,
  `tbl_players_idTBL_PLAYERS` INT NOT NULL,
  PRIMARY KEY (`ID_tbl_teams_has_tbl_playerscol`, `tbl_teams_idTBL_TEAMS`, `tbl_players_idTBL_PLAYERS`),
  INDEX `fk_tbl_teams_has_tbl_players_tbl_players1_idx` (`tbl_players_idTBL_PLAYERS` ASC) VISIBLE,
  INDEX `fk_tbl_teams_has_tbl_players_tbl_teams1_idx` (`tbl_teams_idTBL_TEAMS` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_teams_has_tbl_players_tbl_teams1`
    FOREIGN KEY (`tbl_teams_idTBL_TEAMS`)
    REFERENCES `mydb`.`tbl_teams` (`idTBL_TEAMS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_teams_has_tbl_players_tbl_players1`
    FOREIGN KEY (`tbl_players_idTBL_PLAYERS`)
    REFERENCES `mydb`.`tbl_players` (`idTBL_PLAYERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT T.team_name, P.player_name
FROM tbl_teams_has_tbl_players TP
JOIN tbl_teams T ON TP.tbl_teams_idTBL_TEAMS = T.idTBL_TEAMS
JOIN tbl_players P ON TP.tbl_players_idTBL_PLAYERS = P.idTBL_PLAYERS;


SELECT team , country
FROM tbl_teams
INTO OUTFILE "C:\Users\YURI Lima\Desktop\TIMES\Novo(a) Planilha do Microsoft.csv.xlsx"
FIELDS TERMINATED BY ','
ENCLOSED BY '\"'
LINES TERMINATED BY '\\n';

